<section id="container">

    <div class="pack add-member">

        <h2>Ajouter un Argonaute</h2>

        <form class="new-member-form">

            <label for="argonaute-name">Nom de l'Argonaute</label>
            <input type="text" name="argonaute-name" id="argonaute-name" placeholder="Charalampos">

            <select name="adjective" id="adjective-list">
                <option value="" disabled selected>Choisissez un adjectif</option>
            </select>

            <button type="submit">Ajouter</button>

        </form>

    </div>

    <div class="pack members-list">

        <h2>Liste des Argonautes</h2>

        <ul class="list">

        </ul>

    </div>

</section>