<section id="container">

    <div class="pack add-member">

        <h2>Ajouter un Argonaute</h2>

        <form class="new-member-form">

            <div class="input-container">
                <label for="argonaute-name">Nom de l'Argonaute</label>
                <input type="text" name="argonaute-name" id="argonaute-name" spellcheck="false" autocomplete="off" placeholder="Charalampos">
            </div>

            <div class="input-container">
                <label for="adjective">Choisissez un adjectif</label>
                <select name="adjective" id="adjective-list" size="6"></select>
            </div>

            <button type="submit">Ajouter</button>

        </form>

    </div>

    <div class="pack members-list">

        <h2>Liste des Argonautes</h2>

        <ul class="list">

        </ul>

    </div>

</section>